USE BKEL;

CREATE TABLE IF NOT EXISTS MANAGES_CLASS (
    Id INTEGER NOT NULL AUTO_INCREMENT,
    ClassId VARCHAR(255) NOT NULL,
    LecturerId DECIMAL(7,0) NOT NULL,
    UNIQUE (ClassId, LecturerId),
    PRIMARY KEY (Id),
    FOREIGN KEY (LecturerId) 
        REFERENCES LECTURER(LecturerId)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (ClassId) 
        REFERENCES CLASS(ClassId)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

LOAD DATA INFILE '/mnt/DAE242A5E242862B/Code/db/Excel/manages_class.csv' 
INTO TABLE MANAGES_CLASS
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (ClassId, LecturerId);