USE BKEL;

CREATE TABLE IF NOT EXISTS TEXTBOOK (
    Isbn DECIMAL(13,0) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Field VARCHAR(255),
    PRIMARY KEY (Isbn)
);

LOAD DATA INFILE '/mnt/DAE242A5E242862B/Code/db/Excel/textbook.csv' 
INTO TABLE TEXTBOOK
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (Isbn, Title, Field);