USE BKEL;

CREATE TABLE IF NOT EXISTS WRITES (
    Id INTEGER NOT NULL AUTO_INCREMENT,
    TextbookId DECIMAL(13,0) NOT NULL,
    AuthorId INTEGER NOT NULL,
    UNIQUE (TextbookId, AuthorId),
    PRIMARY KEY (Id),
    FOREIGN KEY (TextbookId) 
        REFERENCES TEXTBOOK(Isbn)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (AuthorId) 
        REFERENCES AUTHOR(AuthorId)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

LOAD DATA INFILE '/mnt/DAE242A5E242862B/Code/db/Excel/writes.csv' 
INTO TABLE WRITES
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (TextbookId, AuthorId);